name: Project Iris - Unit Tests
on: [push]
jobs:
  run-iris-benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Create build directory
        run: mkdir build
      - name: Configure Project
        run: cmake -D CMAKE_BUILD_TYPE=Release -D IRIS_BENCHMARK=ON ..
        working-directory: build
      - name: Build Project
        run: cmake --build .
        working-directory: build
      - name: Run tests
        run: ctest --verbose
        working-directory: build